# Generated by Django 3.1.4 on 2020-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
